// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MicroserviceTemplate.Infrastructure.Data;

#nullable disable

namespace MicroserviceTemplate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119195356_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceTemplate.Features.Tasks.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DueDate");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(2026, 1, 8, 0, 0, 0, TimeSpan.Zero),
                            Description = "Install all necessary tools and dependencies for the project",
                            DueDate = new DateTimeOffset(2026, 1, 10, 0, 0, 0, TimeSpan.Zero),
                            Status = "Done",
                            Title = "Setup Development Environment",
                            UpdatedAt = new DateTimeOffset(2026, 1, 14, 0, 0, 0, TimeSpan.Zero)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(2026, 1, 8, 0, 0, 0, TimeSpan.Zero),
                            Description = "Go through the technical architecture document and provide feedback",
                            DueDate = new DateTimeOffset(2026, 1, 17, 0, 0, 0, TimeSpan.Zero),
                            Status = "InProgress",
                            Title = "Review Architecture Documentation",
                            UpdatedAt = new DateTimeOffset(2026, 1, 14, 0, 0, 0, TimeSpan.Zero)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(2026, 1, 8, 0, 0, 0, TimeSpan.Zero),
                            Description = "Add JWT-based authentication to the API endpoints",
                            DueDate = new DateTimeOffset(2026, 1, 22, 0, 0, 0, TimeSpan.Zero),
                            Status = "Todo",
                            Title = "Implement Authentication",
                            UpdatedAt = new DateTimeOffset(2026, 1, 14, 0, 0, 0, TimeSpan.Zero)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(2026, 1, 8, 0, 0, 0, TimeSpan.Zero),
                            Description = "Create comprehensive unit tests for the service layer",
                            DueDate = new DateTimeOffset(2026, 1, 25, 0, 0, 0, TimeSpan.Zero),
                            Status = "Todo",
                            Title = "Write Unit Tests",
                            UpdatedAt = new DateTimeOffset(2026, 1, 14, 0, 0, 0, TimeSpan.Zero)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(2026, 1, 8, 0, 0, 0, TimeSpan.Zero),
                            Description = "Deploy the application to staging environment for QA testing",
                            DueDate = new DateTimeOffset(2026, 1, 29, 0, 0, 0, TimeSpan.Zero),
                            Status = "Todo",
                            Title = "Deploy to Staging",
                            UpdatedAt = new DateTimeOffset(2026, 1, 14, 0, 0, 0, TimeSpan.Zero)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
