<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ModernMicroservice.AppHost</RootNamespace>
    <IsAspireHost>true</IsAspireHost>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroserviceTemplate\MicroserviceTemplate.csproj" />
  </ItemGroup>

</Project>
